#ifndef DEPENDENCY_SUPPORT_GOV_SANDIA_XYCE_XYCE_CONFIG_H_
#define DEPENDENCY_SUPPORT_GOV_SANDIA_XYCE_XYCE_CONFIG_H_

#define USING_CMAKE 1
#define HAVE_CONFIG_H 1
#define HAVE_ALGORITHM 1
#define HAVE_ALGO_H 1
#define HAVE_BISON 1
#define HAVE_DLFCN_H 1
#define HAVE_FLEX 1
#define HAVE_FLEXIBLE_INSERT 1
#define HAVE_FLOAT_H 1
#define HAVE_GETOPT 1
#define HAVE_DRAND48 1
#define HAVE_INTTYPES_H 1
#define HAVE_IOTA 1
#define HAVE_LIBAMD 1
#define HAVE_LIBEXPR 1
#define HAVE_LIBMETIS 1
#define HAVE_LIBPARMETIS 1
#define HAVE_LIBSUPERLU 1
#define HAVE_LIBSUPERLUDIST 1
#define HAVE_LIBUMFPACK 1
#define HAVE_LIBY12M 1
#define HAVE_LIBZOLTAN 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLINFO 1
#define HAVE_MALLOC_H 1
#define HAVE_MATHIMF_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NAMESPACES 1
#define HAVE_NAN_INF_SUPPORT 1
#define HAVE_PWD_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STL 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_FUNCTIONAL 1
#define HAVE_GETDOMAINNAME 1
#define HAVE_GETHOSTNAME 1
#define HAVE_GETPWUID 1
#define HAVE_ERF 1
#define HAVE_ERFC 1
#define HAVE_UNORDERED_MAP 1
#define HAVE_UNORDERED_SET 1
#define HAVE_STRCASECMP 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UTSNAME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_VALUES_H 1
#define HAVE_EPETRA_MULTIVECTOR_H 1
#define HAVE_IFPACK_CRSRILUK_H 1
#define HAVE_AMESOS_KLU_H 1
#define HAVE_AMESOS_UMFPACK_H 1
#define HAVE_AMESOS_SUPERLU_H 1
#define HAVE_NOX_ABSTRACT_VECTOR_H 1
#define HAVE_LOCA_PARAMETER_VECTOR_H 1
#define NEED_PAIR_H 1

#define PACKAGE
#define PACKAGE_BUGREPORT
#define PACKAGE_NAME
#define PACKAGE_STRING
#define PACKAGE_TARNAME
#define PACKAGE_VERSION

#define Xyce_VERSION_MAJOR 7
#define Xyce_VERSION_MINOR 1
#define Xyce_VERSION_PATCH 0
#define Xyce_VERSION_EXTRA 0

#define Xyce_AMD 1
#define Xyce_BELOS 1
#define Xyce_BTF 1
#define Xyce_NEW_DAE_FORMULATION 1

#define Xyce_PARDISO_MKL 0
#define Xyce_ADMS_MODELS 1
#define Xyce_NEURON_MODELS 1
#define Xyce_SPICE_NORMS 1
#define Xyce_UMFPACK 1
#define Xyce_USE_ISORROPIA 1
#define Xyce_USE_ZOLTAN 1
#define Xyce_USE_PARMETIS 1
#define Xyce_ATHENA 1
#define HAVE_LIBARAENV 1
#define Xyce_ADMS_SENSITIVITIES 1

#define Xyce_NOX_LOCA_SUPPORT 1
#define Xyce_RESTART_NOPACK 1
#define Xyce_USE_FFTW 1
#define Xyce_USE_FFT 1

#endif  // DEPENDENCY_SUPPORT_GOV_SANDIA_XYCE_XYCE_CONFIG_H_
